### ISSUE TITLE
offer app (also) as download

### ISSUE THREAD

**Issue by das-g** [gfroerli/app-android#40]
E.g. as APK file.

So that it can be installed on Android devices without access to Google's PlayStore, too.

**Comment by das-g** [comment]
Bonus points, if each version gets not just a Git tag, bug also a "release" on GitHub with the corresponding build result attached.

**Comment by dbrgn** [comment]
I pushed GH releases for 0.5.1 and 0.6.0.

https://github.com/gfroerli/app-android/releases

**Comment by das-g** [comment]
0.6.0 doesn't seem to have an APK file attached, yet.

**Comment by dbrgn** [comment]
It seems that the upload failed... I re-uploaded it, now it should work.
